repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
      -   id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce  # v8.30.0
    hooks:
      - id: gitleaks