files:
  - source: /src/all/locales/en-UK/common.json
    translation: /src/all/locales/%locale%/%original_file_name%
  - source: /src/all/_locales/en/messages.json
    translation: /src/all/_locales/%two_letters_code%/%original_file_name%
export_languages:
  - de
  - en
  - es
  - fr
  - it
  - ja
  - ko
  - lt
  - nl
  - pl
  - pt-BR
  - ro
  - ru
  - sv
commit_message: '[skip-ci]'
